name = "gymdominator-admin"
compatibility_date = "2023-06-28"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
[build.upload]
format = "directory"

[site]
bucket = ".next/static" 